title: resvg test suite
description: None
source: site
exclude:
  - README.md
  - attributes-table.adoc
  - elements-table.adoc
  - presentation-attributes-table.adoc
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font
